window.RADIANS = "radians";
window.DEGREES = "degrees";
window.CORNER = "corner";
window.CENTER = "center";
window.ANGLE_MODE = window.RADIANS;
window.RECT_MODE = window.CORNER;
window.ELLIPSE_MODE = window.CORNER;
window.PI = Math.PI;
window.TWO_PI = Math.PI * 2;
